const sidebars = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Deployment',
      collapsed: false,
      items: ['deployment/frontend-netlify', 'deployment/docs-netlify', 'deployment/security'],
    },
    {
      type: 'category',
      label: 'Project Docs',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'project-docs' }],
    },
    {
      type: 'category',
      label: 'Reports',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'reports' }],
    },
  ],
};

export default sidebars;
